### ISSUE TITLE
Sync up the system clock when restarting s3fs service to avoid s3 error

### ISSUE THREAD

**Issue by mauricios** [Aplyca/ansible-role-s3fs#1]
See: http://stackoverflow.com/questions/4770635/s3-error-the-difference-between-the-request-time-and-the-current-time-is-too-la

**Comment by mauricios** [comment]
We can add:

``` bash
sudo service ntp stop && sudo ntpdate ntp.ubuntu.com pool.ntp.org && sudo service ntp start
```

Before starting the service

**Comment by mauricios** [comment]
This should be configured in a variable depending on the OS:

``` yaml
#vars/ubuntu.yml
s3fs:
  sync_time_command: "sudo service ntp stop && sudo ntpdate ntp.ubuntu.com pool.ntp.org && sudo service ntp start"
```
