### ISSUE TITLE
Error while trying to download s3fs

### ISSUE THREAD

**Issue by johnscancella** [Aplyca/ansible-role-s3fs#7]
When I try to run your role I get the this error:
```
TASK [aplyca.s3fs : Download s3fs source] **************************************
fatal: [ec2-52-73-143-8.compute-1.amazonaws.com]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'source'\n\nThe error appears to have been in '/private/etc/ansible/roles/aplyca.s3fs/tasks/setup.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Download s3fs source\n  ^ here\n"}
```

here is the ansible-playbook I am running:
```
---
- hosts: localhost
  vars:
    aws_instance_type: "r4.2xlarge"
    # needs to be hvm:ebs-ssd instance type
    aws_ami: "ami-ad4b33bb"
    redundancy: 1
  tasks:

  - name: Provision servers for django
    ec2:
      instance_type: "{{ aws_instance_type }}"
      image: "{{ aws_ami }}"
      region: "us-east-1"
      keypair: "{{ lookup('env','AWS_KEY_PAIR') }}"
      count: "{{ redundancy }}"
      wait: True
    register: django_ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ item.public_dns_name }}"
      groupname: django_instances
    with_items: "{{ django_ec2.instances }}"

  - name: Wait for ssh to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      delay: 30
      timeout: 600
      port: 22
      state: started
    with_items: "{{ django_ec2.instances }}"

- name: Configure django servers
  hosts: django_instances
  user: ubuntu
  gather_facts: True
  vars:
    ansible_ssh_private_key_file: "{{ lookup('env','AWS_SSH_KEY') }}"
    s3fs:
      buckets:
        - mountpoint: /opt/chronam/data/batches/
          bucket: chronam-data-batches
          options: "umask=0022,uid=1000,gid=1000,allow_other,nonempty,use_cache=/tmp"
  roles:
    - aplyca.s3fs
  tasks:
  - name: install dependencies
    apt: name={{ item }} update_cache=True
    with_items:
      - python2.7-dev
      - python-pip
      - libmysqlclient-dev 
      - apache2 
      - libapache2-mod-wsgi 
      - libxml2-dev 
      - libxslt-dev 
      - libjpeg-dev 
      - git-core 
      - graphicsmagick
    become: True

  - name: Git clone chronam code
    git:
      repo: 'https://github.com/LibraryOfCongress/chronam.git'
      dest: /opt/chronam
    become: True

  - name: Set correct permissions
    file:
      recurse: True
      path: /opt/chronam
      owner: ubuntu
      group: ubuntu
    become: True

  - name: Create chronam directories
    file: path="{{ item }}" state="directory" 
    with_items:
      - /opt/chronam/static
      - /opt/chronam/.python-eggs

  - name: Copy LC specific python dependencies
    copy: 
      src: "files/{{ item }}" 
      dest: "/opt/chronam/{{ item }}"
    with_items:
      - django-lc-0.0.3.tar.gz
      - minicts-0.0.1.tar.gz

  - name: Install Chronam
    script: scripts/install_chronam.sh

  - name: create cache and bib directories
    file:
      path: "/opt/chronam/data/{{ item }}"
      state: directory
    with_items:
      - cache
      - bib

  - name: Modify chronam to use new SOLR
    lineinfile:
      path: /opt/chronam/settings_template.py
      regexp: "SOLR = .*"
      line: "SOLR = 'http://{{ groups['solr_instances'][0] }}:8080/solr'"

  - name: Modify chronam to use new MySQL database
    lineinfile:
      path: /opt/chronam/settings_template.py
      insertafter: "'PASSWORD':.*"
      regexp: "'HOST':.*"
      line: "        'HOST': '{{ groups['mysql_instances'][0] }}',"

  - name: Modify chronam to use correct MySQL password
    lineinfile:
      path: /opt/chronam/settings_template.py
      regexp: "'PASSWORD':.*"
      line: "        'PASSWORD': '{{ hostvars['localhost']['db_password'] }}',"

  - name: Modify apache2 config to allow access to root directory
    replace:
      path: /etc/apache2/apache2.conf
      regexp: "(<[dD]irectory />[^<]*)Require all denied"
      replace: '\1Require all granted'
    become: True

  - name: restart apache
    service:
      name: apache2
      state: restarted
    become: True

  - name: Run initial chronam config script
    script: scripts/django_initial_setup.sh

  - name: Remove temp directory
    file:
      path: /var/tmp/django_cache
      state: absent
    become: True
```
