### ISSUE TITLE
Mounting not working, no buckets created

### ISSUE THREAD

**Issue by jadbaz** [Aplyca/ansible-role-s3fs#8]
This is my playbook:
_s3fs.yml_
```
---
-
  hosts: all
  become: true
  vars_files:
    - vars/aws.yml
  roles:
    - role: Aplyca.S3fs
      buckets:
        - mountpoint: /mnt/s3fs
          bucket: "{{aws_bucket_name}}"
          accessKeyId: "{{aws_access_key_id}}"
          secretAccessKey: "{{aws_secret_access_key}}"
          options: "allow_other,use_cache=/tmp,max_stat_cache_size=100000,uid=33,gid=33,umask=002"          
```

`ansible-playbook s3fs.yml` runs perfectly with no issues however mounting is simply not happening.
It seems that no buckets are actually being created (in debug: `buckets = []`)
Moreover, `/etc/passwd-s3fs` does not get created

Here's the debug log: [ansible-role-s3fs-bucket-not-found-2017-07-25.txt](https://github.com/Aplyca/ansible-role-s3fs/files/1173369/ansible-role-s3fs-bucket-not-found-2017-07-25.txt)

Vars:
- **ansible**: 2.3.1.0
- **ansible.cfg**: `hash_behaviour = merge`
- **target OS**: Ubuntu Sever 16.04

**Comment by jadbaz** [comment]
It seems that I was simply missing the s3fs level in the variables. So the new one becomes
_s3fs.yml_
```
---
-
  hosts: all
  become: true
  vars_files:
    - vars/aws.yml
  roles:
    - role: Aplyca.S3fs
      s3fs:
        buckets:
          - mountpoint: /mnt/s3fs
            bucket: "{{aws_bucket_name}}"
            accessKeyId: "{{aws_access_key_id}}"
            secretAccessKey: "{{aws_secret_access_key}}"
            options: "allow_other,use_cache=/tmp,max_stat_cache_size=100000,uid=33,gid=33,umask=002"          
```
