### ISSUE TITLE
Problems with variables from defaults/ and vars/

### ISSUE THREAD

**Issue by computerlyrik** [Aplyca/ansible-role-s3fs#9]
Hey there.

I stumbled upon the issue mentioned here: https://github.com/Aplyca/ansible-role-s3fs/issues/3
So i set the ```hash_behaviour=merge```

It did not help!!! Same error: 
```
FAILED! => {
    "msg": "'dict object' has no attribute 'dependencies'"
}
```

During this my s3fs dict shows (with merge enabled and disabled):
```
    "s3fs": {
        "buckets": [
            {
                "accessKeyId": "accessKeyId", 
                "bucket": "s3fs", 
                "mountpoint": "/srv/mount", 
                "options": "allow_other,use_cache=/tmp,max_stat_cache_size=100000,uid=33,gid=33,umask=002", 
                "secretAccessKey": "secretAccessKey"
            }
        ]
    }
```
I removed the s3fs bucket configuration. Now something gets confiured - ```vars/```

```
{
    "s3fs": {
        "daemon": "/usr/local/bin/s3fs", 
        "dependencies": [
            "unzip", 
            "fuse", 
            "libssl-dev", 
            "pkg-config", 
            "build-essential", 
            "libfuse-dev", 
            "libcurl4-openssl-dev", 
            "libxml2-dev", 
            "mime-support", 
            "automake", 
            "libtool", 
            "ntp"
        ], 
        "passwd_file": "/etc/passwd-s3fs"
    }
}
```

But now it fails with
```
FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'source'\n\nThe error appears to have been in '/[...]/roles/Aplyca.S3fs/tasks/setup.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Download s3fs source\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'source'"
}
```

Please help! Copying all variables to the playbook i use the role in, is not a long-term soluiton!

On ansible 2.4.3.0 with the playbook conaining only:

```
  roles:
    - role: aplyca.s3fs
      s3fs:
        buckets:
          - mountpoint: "{{ someMountpoint }}"
            bucket: s3fs
            accessKeyId: "accessKeyId"
            secretAccessKey: "secretAccessKey"
            options: "allow_other,use_cache=/tmp,max_stat_cache_size=100000,uid=33,gid=33,umask=002"
```
